### ISSUE TITLE
fix demo docker image

### ISSUE THREAD

**Issue by henrywangx** [minio/openlake#1]
Hi dilverse, I really like this repo and your work.

And I follow your [guide](https://github.com/minio/openlake/blob/main/spark/spark-with-minio.md), found the `main.py` in docker image `openlake/sparkjob-demo:3.3.2`  is inconsistent to your guide.

```bash
spark = SparkSession.builder.config(conf=conf).getOrCreate()
# should be 
spark = SparkSession.builder.getOrCreate()
```

**Comment by dilverse** [comment]
Thanks @henrywangx I will get it fixed

**Comment by dilverse** [comment]
Fixed
